//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class education
    {
        public long id_education { get; set; }
        public long id_employee { get; set; }
        [Required]
        public string degree_name { get; set; }
        public Nullable<decimal> score { get; set; }
        public Nullable<decimal> scale { get; set; }
        public Nullable<System.DateTime> passing_year { get; set; }
        
        [Required]
        public string institute_name { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
