//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_tag
    {
        public long id_employee_tag { get; set; }
        public string tag_name { get; set; }
        public long id_employee { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
