//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class employee
    {
        public employee()
        {
            this.educations = new HashSet<education>();
            this.job_applied = new HashSet<job_applied>();
            this.job_applicant = new HashSet<job_applicant>();
            this.employee_tag = new HashSet<employee_tag>();
        }
    
        public long id_employee { get; set; }
        public long id_user { get; set; }
        public Nullable<int> age { get; set; }
        public string sex { get; set; }
        [Required]
        public string first_name { get; set; }
        [Required]
        public string last_name { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
        public string contact_number { get; set; }
        public string local_address { get; set; }
        public string parmanent_address { get; set; }
    
        public virtual ICollection<education> educations { get; set; }
        public virtual ICollection<job_applied> job_applied { get; set; }
        public virtual ICollection<job_applicant> job_applicant { get; set; }
        public virtual ICollection<employee_tag> employee_tag { get; set; }
        public virtual user user { get; set; }
    }
}
