//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class employeer
    {
        public employeer()
        {
            this.job_circular = new HashSet<job_circular>();
        }
    
        public long id_employeer { get; set; }
        public long id_user { get; set; }
        
        [Required]
        public string office_name { get; set; }
        [Required]
        public string contact_number { get; set; }
        
        [Required]
        public string office_address { get; set; }
    
        public virtual ICollection<job_circular> job_circular { get; set; }
        public virtual user user { get; set; }
    }
}
