//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_circular
    {
        public job_circular()
        {
            this.job_applicant = new HashSet<job_applicant>();
            this.job_applied = new HashSet<job_applied>();
            this.job_circular_tag = new HashSet<job_circular_tag>();
        }
    
        public long id_job_circular { get; set; }
        public string title { get; set; }
        public string salary { get; set; }
        public System.DateTime deadline { get; set; }
        public Nullable<int> experience { get; set; }
        public Nullable<int> vacancy { get; set; }
        public long id_employeer { get; set; }
    
        public virtual employeer employeer { get; set; }
        public virtual ICollection<job_applicant> job_applicant { get; set; }
        public virtual ICollection<job_applied> job_applied { get; set; }
        public virtual ICollection<job_circular_tag> job_circular_tag { get; set; }
    }
}
