//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_management_final
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public user()
        {
            this.employees = new HashSet<employee>();
            this.employeers = new HashSet<employeer>();
        }
    
        public long id_user { get; set; }

        
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]

        public string email { get; set; }

        [Required(ErrorMessage = "username can't be empty")]
        public string username { get; set; }
        public string password { get; set; }
        public string user_role { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<employeer> employeers { get; set; }
    }
}
